INSERT INTO products (name, description, category, brand, price, available_quantity) VALUES
('Wireless Mouse', 'Ergonomic wireless mouse with 2.4GHz connectivity', 'ELECTRONICS', 'LogiTech', 999.00, 120),
('Bluetooth Headphones', 'Over-ear headphones with noise cancellation', 'ELECTRONICS', 'Sony', 5999.00, 60),
('Smartphone', 'Latest 5G smartphone with AMOLED display', 'ELECTRONICS', 'Samsung', 32999.00, 35),
('Laptop Backpack', 'Water-resistant laptop bag with multiple compartments', 'FASHION', 'Wildcraft', 1899.00, 75),
('Men’s Running Shoes', 'Lightweight running shoes for men', 'FASHION', 'Nike', 4999.00, 45),
('Women’s Handbag', 'Leather handbag with spacious design', 'FASHION', 'Baggit', 2599.00, 52),
('Washing Machine', '6.5kg fully automatic front load washing machine', 'HOME_APPLIANCES', 'LG', 28999.00, 20),
('Microwave Oven', '23L convection microwave with smart inverter', 'HOME_APPLIANCES', 'IFB', 11499.00, 28),
('Vacuum Cleaner', 'Bagless vacuum cleaner with HEPA filter', 'HOME_APPLIANCES', 'Eureka Forbes', 8499.00, 15),
('LED Bulb Pack', 'Set of 4 energy-efficient LED bulbs', 'HOME_APPLIANCES', 'Philips', 499.00, 180),
('Face Moisturizer', 'Hydrating moisturizer for all skin types', 'BEAUTY', 'Nivea', 349.00, 140),
('Shampoo', 'Anti-dandruff shampoo with cooling menthol', 'BEAUTY', 'Head & Shoulders', 299.00, 110),
('Perfume', 'Long-lasting fragrance for daily use', 'BEAUTY', 'Calvin Klein', 4599.00, 30),
('Self-Help Book', 'Inspiring book on personal growth', 'BOOKS', 'Penguin', 399.00, 85),
('Fiction Novel', 'Bestselling fantasy novel by popular author', 'BOOKS', 'HarperCollins', 699.00, 40),
('Cookware Set', 'Non-stick cookware set with 3 pans', 'HOME_APPLIANCES', 'Prestige', 2399.00, 60),
('Cricket Bat', 'Professional-grade English willow bat', 'SPORTS', 'SS', 5499.00, 22),
('Football', 'Durable synthetic leather football', 'SPORTS', 'Nivia', 799.00, 50),
('Yoga Mat', 'Anti-slip yoga mat with carry strap', 'SPORTS', 'Reebok', 1299.00, 100),
('Protein Powder', 'Whey protein for muscle recovery', 'SPORTS', 'Optimum Nutrition', 6999.00, 18),
('Cooking Oil', 'Sunflower oil for healthy cooking', 'GROCERY', 'Fortune', 189.00, 210),
('Basmati Rice', 'Premium long-grain basmati rice 5kg', 'GROCERY', 'Daawat', 549.00, 150),
('Chocolate Pack', 'Assorted dark chocolate gift pack', 'GROCERY', 'Lindt', 899.00, 90),
('Toy Car', 'Remote-controlled toy car for kids', 'TOYS', 'Hot Wheels', 1599.00, 70),
('Teddy Bear', 'Soft plush teddy bear 2ft tall', 'TOYS', 'Archies', 799.00, 85),
('Puzzle Game', '1000-piece jigsaw puzzle for adults', 'TOYS', 'Funskool', 499.00, 65),
('Air Fryer', 'Low-oil digital air fryer 4L', 'HOME_APPLIANCES', 'Philips', 9499.00, 25),
('Gaming Keyboard', 'Mechanical keyboard with RGB backlight', 'ELECTRONICS', 'Corsair', 8999.00, 40),
('Smartwatch', 'Fitness tracking smartwatch with AMOLED display', 'ELECTRONICS', 'Amazfit', 7499.00, 50),
('Bluetooth Speaker', 'Portable speaker with deep bass and long battery life', 'ELECTRONICS', 'boAt', 1999.00, 90);
